<?php

/**
 * Implements hook_install().
 */
function debut_social_install() {
  // Set captcha to forward form.
  module_load_include('inc', 'captcha');
  captcha_set_form_id_setting('forward_form', 'default');
}

/**
 * Implements hook_enable().
 */
function debut_social_enable() {
  $modules = module_list();
  module_load_include('inc', 'debut_social', 'debut_social.util');
  debut_social_add_node_types($modules);
}
